name: Build
on:
  push:
    branches: [ "**" ]

jobs:
  build-bookmark-api:
    name: Build bookmark-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check directory structure
        run: ls -alR

